version: "3.8"

services:
  # Mysql
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: discharge
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # JDK 21 + Alpine
  backend:
    image: eclipse-temurin:21-jdk-alpine
    container_name: java_container
    environment:
      # Acesso ao Container DB
      DB_URL: jdbc:mysql://db/discharge
      DB_USER: root
      DB_PASSWORD: 123
      # Acesso ao S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    working_dir: /app
    command: >
      /bin/sh -c "
      apk add --no-cache git &&
      if [ ! -d .git ]; then git clone https://github.com/Grupo-5-High-Five/discharge-backend.git .; fi &&
      until java -jar target/discharge-1.0-SNAPSHOT-jar-with-dependencies.jar; do sleep 5; done"
    ports:
      - "5555:5555"
    depends_on:
      - db

  # Node.js + Alpine
  frontend:
    image: node:20.18.0-alpine
    container_name: node_container
    environment:
      AMBIENTE_PROCESSO: desenvolvimento
      DB_HOST: db
      DB_DATABASE: discharge
      DB_USER: user
      DB_PASSWORD: 123
      DB_PORT: 3306
      APP_PORT: 3333
      APP_HOST: localhost
    working_dir: /app
    command: >
      /bin/sh -c "
      apk add --no-cache git &&
      if [ ! -d .git ]; then git clone https://github.com/Grupo-5-High-Five/discharge-web.git .; fi &&
      npm install &&
      npm start"
    ports:
      - "3333:3333"
    depends_on:
      - db

volumes:
  db_data:
