version: "3.8"

services:
  # Mysql
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: discharge
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u",
          "root",
          "-p123",
          "-h",
          "127.0.0.1",
          "-e",
          "SHOW DATABASES;",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # JDK 21 + Alpine
  backend:
    image: zapss/discharge-jdk:1.0
    container_name: java_container
    environment:
      # Acesso ao Container DB
      DB_URL: jdbc:mysql://db/discharge
      DB_USER: root
      DB_PASSWORD: 123
      # Acesso ao S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    ports:
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy

  # Node.js + Alpine
  frontend:
    image: zapss/discharge-nodejs:1.0
    container_name: node_container
    environment:
      AMBIENTE_PROCESSO: desenvolvimento
      DB_HOST: db
      DB_DATABASE: discharge
      DB_USER: user
      DB_PASSWORD: 123
      DB_PORT: 3306
      APP_PORT: 3333
      APP_HOST: localhost
      MEU_EMAIL: atendimentohighfive@gmail.com
      MINHA_SENHA: upcyjphafxzzoslh
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
