# Parâmetro com o nome da Chave de Acesso a EC2
Parameters:
  KeyName:
    Description: "Insira a chave de acesso:"
    Type: String

Resources:
  # Criação e configuração de rede VPC
  EC2Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true

  EC2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EC2Vpc
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true

  EC2InternetGateway:
    Type: AWS::EC2::InternetGateway

  EC2GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref EC2Vpc
      InternetGatewayId: !Ref EC2InternetGateway

  EC2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EC2Vpc

  EC2Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref EC2RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref EC2InternetGateway

  EC2SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref EC2Subnet
      RouteTableId: !Ref EC2RouteTable

  # Configurações dos Grupos de Segurança
  EC2GrupoSeguranca:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso liberado para SSH e portas do projeto Discharge
      VpcId: !Ref EC2Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "3333"
          ToPort: "3333"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "5555"
          ToPort: "5555"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: "0.0.0.0/0"

  # Configurações da EC2
  EC2Instancia:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-0866a3c8686eaeeba
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref EC2GrupoSeguranca
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
      SubnetId: !Ref EC2Subnet
      Tags:
        - Key: Name
          Value: discharge-ec2-aws
